---
# handlers file for db
- name: Restart mysql
  service:
    name: mysql
    state: restarted

- name: Flush privileges
  shell: >
    mysql -u root -NBe
    'FLUSH PRIVILEGES;'

- name: Reload AppArmor
  shell: >
    apparmor_parser -r /etc/apparmor.d/usr.sbin.mysqld
