---
# tasks file for docker
- name: update apt list
  apt:
    update_cache: yes

- name: Install prerequisites
  apt:
    name: [
      'apt-transport-https',
      'ca-certificates',
      'curl',
      'gnupg2',
      'software-properties-common'
    ]
    update_cache: yes

- name: Add Docker GPG key
  apt_key: url=https://download.docker.com/linux/ubuntu/gpg

- name: Add Docker APT repository
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/{{ansible_distribution|lower}} {{ansible_distribution_release}} stable

- name: Install Docker
  apt:
    name: docker-ce
    update_cache: yes

- name: Replace docker daemon file
  template:
    src: docker_daemon.json.j2
    dest: /etc/docker/daemon.json
  notify: Restart docker

- name: Install pip
  apt:
    name: python3-pip
    update_cache: yes
    state: latest

- pip:
    name: docker
    umask: "0022"
  become: yes

- name: Set fales
  copy:
    src: "{{ item }}"
    dest: "/opt/"
  with_items: 
      - ".app.env" 

- name: Replace docker daemon file
  template:
    src: docker-compose.yml.j2
    dest: /opt/docker-compose.yml

- name: Join to swarm
  docker_swarm:
    state: present
    advertise_addr: "{{swarm_address}}"
  notify: Restart docker

- name: Login to docker
  docker_login:
    registry: "{{docker_host}}"
    username: "{{docker_username}}"
    password: "{{docker_password}}"

- name: Pull integrator image
  docker_image:
    name: "{{image_name}}"
    source: pull

- name: Deploy integrator stack
  command: docker stack deploy -c /opt/docker-compose.yml integrator
  become: yes
  become_user: root
