---
# tasks file for db
- name: MySQL | Install 5.7
  apt:
    name: ['mysql-server-5.7']
    state: present

- name: Apparmor | Confgure
  template:
    src: apparmor-mysqld.conf.j2
    dest: /etc/apparmor.d/usr.sbin.mysqld
  notify: Reload AppArmor

- name: MySQL | Update my.cnf
  template:
    src: my.cnf.j2
    dest: /etc/mysql/my.cnf
  notify: Restart mysql

- name: MySQL | Update user and password
  shell: >
    mysql -u root -NBe
    'GRANT ALL PRIVILEGES ON *.* TO "{{ mysql_root_username }}"@"%"
    IDENTIFIED BY "{{ mysql_root_password }}";'
  notify: Flush privileges
