---
# tasks file for swarm_node
- debug: msg="trigger start docker daemon"
  notify: start_docker
  changed_when: true

- name: Create log files
  file:
    path: "/var/log/{{item}}"
    state: touch
    mode: '0777'
  with_items:
    - thin.log
    - thin.0.log
    - thin.9292.log

- name: Create /opt directory
  file:
    path: /opt
    state: directory

- name: Set environment
  template:
    src: environment.j2
    dest: /etc/profile.d/env.sh

- name: Copy env file
  template:
    src: app.env.j2
    dest: /opt/app.env

- name: Join Swarm
  shell:
    cmd: docker swarm join --token {{join_token}} {{swarm_manager}} || true

