# @todo organize gems.
source 'https://rubygems.org'


gem 'acts_as_list'
gem 'cancan'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '4.2.0'
# Use mysql as the database for Active Record
gem 'mysql2', '~> 0.3.18'
# Use SCSS for stylesheets
gem 'sass-rails', '~> 4.0.3'
# Use Uglifier as compressor for JavaScript assets
gem 'uglifier', '>= 1.3.0'
# Use CoffeeScript for .js.coffee assets and views
gem 'coffee-rails', '~> 4.0.0'
# See https://github.com/sstephenson/execjs#readme for more supported runtimes
gem 'therubyracer',  platforms: :ruby
gem 'devise',           '~> 4.7.1'
gem 'devise_invitable', '~> 1.5.2'
# Use jquery as the JavaScript library
gem 'jquery-rails'
# Turbolinks makes following links in your web application faster.
# Read more: https://github.com/rails/turbolinks
gem 'turbolinks'
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 2.0'
# bundle exec rake doc:rails generates the API under doc/api.
gem 'sdoc', '~> 0.4.0',          group: :doc
gem 'execjs'
gem 'jquery-atwho-rails'
gem "sentry-raven"

gem "rails-settings-cached"
# UI components and related gems
gem 'rails4-autocomplete'
gem 'will_paginate', '~> 3.0.6'
gem 'will_paginate-bootstrap'
gem 'country_select'
gem 'countries', '1.2.5', :require => 'countries/global'
gem 'jquery-datatables-rails', git: 'https://github.com/rweng/jquery-datatables-rails', branch: 'master'
gem 'ajax-datatables-rails'
gem 'numo-narray', git: 'https://github.com/ruby-numo/numo-narray', branch: 'master'
gem 'remotipart', '~> 1.2'
gem 'best_in_place', github:'widernet/best_in_place', branch: 'rails-4'

# Background processing
gem 'sinatra', require: false
gem 'sidekiq'
gem 'sidekiq_status'
gem 'whenever', :require => false

# Multi-tenancy for Rails and ActiveRecord
gem 'apartment'

# File generation, management, and storage
gem 'wicked_pdf'
gem 'wkhtmltopdf-binary'
gem 'plutus',  git: 'https://github.com/RailsCarma/plutus.git'
gem 'paperclip', git: 'https://github.com/thoughtbot/paperclip'
gem 'aws-sdk'
gem 'rubyzip', '~> 1.1.0'
gem 'roo'
gem 'axlsx', '2.1.0.pre'
gem 'axlsx_rails'

# API related gems
gem 'apipie-rails'
gem 'fast_jsonapi'
gem 'active_model_serializers', '~> 0.9.0'

# Activity logs
gem 'audited'

# Soft delete
gem "paranoia", "~> 2.2"

gem 'activerecord-import', '~> 0.15.0'
gem 'activerecord-session_store', github: 'rails/activerecord-session_store'
gem "cocoon"

# To make search easier
gem 'ransack'

#for select2
gem "select2-rails"

# for better api responses
# https://github.com/nesquena/rabl
gem 'rabl'
gem 'oj'

# language detection
gem "cld"

gem 'doorkeeper'
gem 'doorkeeper-jwt'

group :development do
  # Spring speeds up development by keeping your application running in the background.
  # Read more: https://github.com/rails/spring
  gem 'spring'
  gem 'letter_opener'
  # Deployment gems
  gem 'capistrano', '3.4'
  gem 'capistrano-rails'
  gem 'capistrano-bundler'
  gem 'sshkit-sudo'
  gem 'capistrano-rvm'
  gem 'airbrussh', :require => false
  gem 'pry'
end

# Use debugger
group :development, :test do
  gem 'byebug'
end

group :production, :staging do
  gem 'unicorn', '4.7.0'
  gem 'rack-health'
end

group :production do
  gem 'scout_apm'
end

gem 'appsignal'
gem 'bugsnag'

# Wicked gem helps us to make multi step forms. E.g used it in onBoarding feature'
gem 'wicked'

gem 'rake', '~>11.2', '>=11.2.2'