- hosts: all
  become: yes
  vars_files:
    - vars/docker_vars.yml
  tasks:
    - name: update apt list
      apt:
        update_cache: yes

    - name: Install prerequisites
      apt:
        name: ['apt-transport-https','ca-certificates','curl','gnupg2','software-properties-common']
        update_cache: yes

    - name: Add Docker GPG key
      apt_key: url=https://download.docker.com/linux/ubuntu/gpg

    - name: Add Docker APT repository
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/{{ansible_distribution|lower}} {{ansible_distribution_release}} stable

    - name: Install Docker
      apt:
        name: docker-ce
        update_cache: yes

    - name: Replace docker daemon file
      template:
        src: templates/docker_daemon.json.j2
        dest: /etc/docker/daemon.json

    - name: Restart docker daemon
      service:
        name: docker
        state: restarted

    - pip:
        name: docker
        umask: "0022"
      become: yes

    - name: Pull image web
      docker_image:
        name: 192.168.56.10:5000/qoyod:latest
        source: pull

    - name: Join to swarm
      docker_swarm:
        state: join
        advertise_addr: "{{ docker_host }}"
        join_token: "{{ join_token }}"
        remote_addrs: [ "{{ docker_host }}" ]
